### ISSUE TITLE
mkdir: cannot create directory '.aws': File exists

### ISSUE THREAD

**Issue by tristanbrown** [futurice/docker-volume-backup#16]
If I leave this container up for a few days, it will eventually get stuck in a loop, giving this error message:
`mkdir: cannot create directory '.aws': File exists`

The only way I've found to break it out of this loop is to remove the container completely and create it fresh. 

My docker-compose.yml file contains this:
```
backup:
    image: futurice/docker-volume-backup:2.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - mongotemp:/backup/mongodb:ro
      - ${BACKUP_DIR}:/archive
    environment:
      - BACKUP_CRON_EXPRESSION=${BACKUP_CRON_EXPRESSION}
    restart: always
mongodb:
    image: mongo:4.2
    ports:
      - "37017:27017"
    volumes:
      - mongodata:/data/db
      - mongotemp:/tmp/mongodb
    labels:
      # First, safely backs up from data to temp using db-specific tool.
      # Then temp is backed up externally.
      - docker-volume-backup.exec-pre-backup=mongodump --archive=/tmp/mongodb/mongo.dump
      - docker-volume-backup.exec-post-backup=rm -rfv /tmp/mongodb
      # Restore backup by cp into mongodb container, $ mongorestore --archive=mongo.dump
    restart: always
```
